### ISSUE TITLE
add status information to reflect the number of AZs a cluster is spread across

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#360]
# Description

Add a status field in the NATS-CR to reflect the current number of AZs used by the NATS cluster

# Acceptance
- watch the Pods created for the NATS cluster
- sum up the number of different AZs used by the K8S-Nodes the NATS Pods are scheduled on 
- for clusters with 3 or more Nodes set a condition reflecting if the cluster is HACapable (3 AZs (or more for bigger cluster sizes) are currently used)
- export the number of AZs used by NATS Pods as a metric 
  - either create a query for the monitoring system
  - or create a configuration to reflect the newly introduced status field using kubestate-metrics

**Comment by mfaizanse** [comment]
## Status
### Different zones
```
status:
  availabilityZonesUsed: 3
  conditions:
  - lastTransitionTime: "2024-04-23T12:12:55Z"
    message: StatefulSet is ready
    reason: Available
    status: "True"
    type: StatefulSet
  - lastTransitionTime: "2024-04-23T12:12:55Z"
    message: NATS is deployed
    reason: Deployed
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-23T12:12:55Z"
    message: NATS is deployed in different availability zones.
    reason: Deployed
    status: "True"
    type: AvailabilityZones
  state: Ready
  url: nats://eventing-nats.kyma-system.svc.cluster.local:4222
```

### Same zones
```
xxx
```
