### ISSUE TITLE
Provision PodDisruptionBudget

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#92]
## Description

Without proper PodDisruptionBudget configured, k8s evictes NATS pods on the nodes without waiting for a replacement pods to be created.

Check NATS official helm charts: [link](https://github.com/nats-io/k8s/blob/main/helm/charts/nats/files/pod-disruption-budget.yaml)

## Acceptance
- [x] Provision a PodDiscruptionBudget along the sts that ensures 2/3 of the cluster-pods need to be available

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name:  ...
spec:
  maxUnavailable: 33%
  selector:
    matchLabels:
      app: ...
```
